name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add .nojekyll file
        run: touch .nojekyll

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: '.'                 # Directory to deploy from (your root in this case)
          preview-branch: gh-pages        # Branch to deploy preview content
          umbrella-dir: pr-preview        # Folder under branch to contain PR previews

      - name: Find Existing Comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Preview deployment'

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🚀 Preview deployment

            Your PR is deployed to a temporary preview environment!

            🌐 **[View Preview](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-preview/pr-${{ github.event.pull_request.number }}/)**

            ℹ️ _This preview updates automatically when new commits are pushed._
          edit-mode: replace
